name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  display-software-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display software versions
      run: |
        echo "Node.js version:"
        node --version
        echo "Python version:"
        python --version

  display-dbms-versions:
    needs: display-software-versions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display DBMS version
      run: |
        echo "PostgreSQL version:"
        psql --version
 
