name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  check-smartphone-os:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display Android OS version
      run: |
        echo "Версія ОС Android:"
        adb shell getprop ro.build.version.release || echo "Немає доступу до Android ОС"
  
  check-server-application:
    needs: check-smartphone-os
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display Linux OS version
      run: |
        echo "Версія ОС Linux:"
        uname -r
    
    - name: Display Apache Tomcat version
      run: |
        echo "Версія Apache Tomcat:"
        curl -s http://localhost:8080 | grep "Apache Tomcat" || echo "Tomcat не встановлено або недоступний"

  check-database-server:
    needs: check-server-application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display MySQL version
      run: |
        echo "Версія MySQL:"
        mysql --version || echo "MySQL не встановлено або недоступний"
