name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Apache Tomcat Version
        run: |
          echo "Apache Tomcat Version:"
          curl --version # Замініть цю команду на команду, яка дійсно зможе перевірити версію Tomcat

  database_versions:
    runs-on: ubuntu-latest
    needs: data_processing_versions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print MySQL Version
        run: mysql --version
